name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: test
      run: make test
    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: static-build
        path: ./netaggregate

